[project]
name = "bateman-cycle-optimizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "scipy>=1.16.3",
    "typer>=0.20.0",
]

[tool.setuptools]
packages = ["optimizer"]

[tool.uv]
package = true

[project.scripts]
optim = "optimizer.scripts.run_bateman:app"
